### ISSUE TITLE
[User Story 3] Listing Page

### ISSUE THREAD

**Issue by daniakalomiris** [Luigi1000/SOEN-341_Project_Team-A#104]
- [x] Redirect to correct item page after submit #105 
- [x] Display user's name in item.php #106
- [x] Display user's profile picture in item.php #107
