### ISSUE TITLE
[User Story 5] Messaging between users

### ISSUE THREAD

**Issue by daniakalomiris** [Luigi1000/SOEN-341_Project_Team-A#145]
As a user, I would like to have two-way communication with a seller about a listing. It should be accessible from a new page for reading/writing new messages.

- [x] Create table in database message information #146 
- [x] Create an inbox page #147
- [x] Display messages with chosen user #148
- [x] Add ability to send message on inbox page #149 
- [x] Link contact button on item listing to inbox #150

**Comment by daniakalomiris** [comment]
- Users can send messages to seller from item page and messages are displayed on Inbox page
- Message information stored in 'inbox' table in database
