### ISSUE TITLE
[User Story 2] User Profile

### ISSUE THREAD

**Issue by daniakalomiris** [Luigi1000/SOEN-341_Project_Team-A#99]
As a user, I want to see my user profile after registration so that I can edit the user's information.

- [ ] Fix database warning when editing user profile  #100
- [ ] Add profile picture to each user #101
- [ ] Display profile picture next to each seller's username #102
- [ ] Modify login so that logged out users only access the first two tabs #103

**Comment by Yang8547** [comment]
In editing user profile tag, I think we should also allow user to edit # **city name** and # **province** besides address. Since we have these two field in user table and we need to display them as part of item info in listings.

**Comment by daniakalomiris** [comment]
Good idea. I will add the tasks to include fields for the city and province and to display both of these in each item listing.
